import { defineField, defineType } from 'sanity';

export default defineType({
  name: 'homePage',
  title: '首页',
  type: 'document',
  groups: [
    { name: 'hero', title: '首屏 Banner' },
    { name: 'content', title: '首页模块' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'hero',
      title: 'Hero / Banner（推荐）',
      type: 'heroBanner',
      group: 'hero',
      description: '配置后优先于此处展示；下方旧字段仅兼容存量数据',
    }),
    defineField({
      name: 'heroImage',
      title: '首屏背景图（旧版）',
      type: 'image',
      description:
        '与 Hero 组件一致：全宽 cover、约一屏高。建议 2400×1350 px（16∶9）或更大；重要视觉偏中下，避开顶栏。',
      options: { hotspot: true },
      group: 'hero',
    }),
    defineField({
      name: 'heroTitle',
      title: '首屏主标题（旧版）',
      type: 'text',
      rows: 3,
      group: 'hero',
    }),
    defineField({
      name: 'heroSubtitle',
      title: '首屏副标题（旧版）',
      type: 'text',
      rows: 3,
      group: 'hero',
    }),
    defineField({
      name: 'trustBadge',
      title: '首屏认证角标（旧版）',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'featuredProducts',
      title: '首页精选产品',
      type: 'array',
      group: 'content',
      of: [{ type: 'reference', to: [{ type: 'product' }] }],
      validation: (r) => r.max(12),
    }),
    defineField({
      name: 'featuredCaseStudies',
      title: '首页精选案例',
      type: 'array',
      group: 'content',
      of: [{ type: 'reference', to: [{ type: 'caseStudy' }] }],
      validation: (r) => r.max(8),
    }),
    defineField({
      name: 'featuredFaqs',
      title: '首页 FAQ 条目',
      type: 'array',
      group: 'content',
      of: [{ type: 'reference', to: [{ type: 'faq' }] }],
    }),
    defineField({
      name: 'faqSectionTitle',
      title: '首页 FAQ 区块标题',
      type: 'string',
      group: 'content',
      initialValue: '常见问题',
    }),
    defineField({
      name: 'ctaSection',
      title: '首页 CTA 区块',
      type: 'object',
      group: 'content',
      fields: [
        defineField({ name: 'title', title: '标题', type: 'string' }),
        defineField({ name: 'subtitle', title: '副标题', type: 'text', rows: 2 }),
        defineField({ name: 'buttonLabel', title: '按钮文案', type: 'string' }),
        defineField({ name: 'buttonUrl', title: '按钮链接', type: 'string' }),
      ],
    }),
    defineField({
      name: 'content',
      title: '首页文案覆盖（可选）',
      type: 'object',
      group: 'content',
      description: '留空时前台使用 i18n 默认文案；填写后中文前台优先显示这里的文案。',
      fields: [
        defineField({ name: 'trustLine', title: '信任背书行文案', type: 'string' }),
        defineField({ name: 'serviceEyebrow', title: '服务模块眉题', type: 'string' }),
        defineField({ name: 'serviceTitle', title: '服务模块标题', type: 'string' }),
        defineField({ name: 'serviceLead', title: '服务模块导语', type: 'text', rows: 2 }),
        defineField({ name: 'oemTitle', title: 'OEM 卡片标题', type: 'string' }),
        defineField({ name: 'oemCardLead', title: 'OEM 卡片说明', type: 'text', rows: 2 }),
        defineField({ name: 'odmTitle', title: 'ODM 卡片标题', type: 'string' }),
        defineField({ name: 'odmCardLead', title: 'ODM 卡片说明', type: 'text', rows: 2 }),
        defineField({ name: 'obmTitle', title: 'OBM 卡片标题', type: 'string' }),
        defineField({ name: 'obmCardLead', title: 'OBM 卡片说明', type: 'text', rows: 2 }),
        defineField({ name: 'coreEyebrow', title: '核心实力模块眉题', type: 'string' }),
        defineField({ name: 'coreTitle', title: '核心实力模块标题', type: 'string' }),
        defineField({ name: 'coreLead', title: '核心实力模块导语', type: 'text', rows: 2 }),
        defineField({ name: 'whyEyebrow', title: '优势模块眉题', type: 'string' }),
        defineField({ name: 'whyTitle', title: '优势模块标题', type: 'string' }),
        defineField({ name: 'whyLead', title: '优势模块导语', type: 'text', rows: 2 }),
        defineField({ name: 'why1t', title: '优势1标题', type: 'string' }),
        defineField({ name: 'why1d', title: '优势1说明', type: 'text', rows: 2 }),
        defineField({ name: 'why2t', title: '优势2标题', type: 'string' }),
        defineField({ name: 'why2d', title: '优势2说明', type: 'text', rows: 2 }),
        defineField({ name: 'why3t', title: '优势3标题', type: 'string' }),
        defineField({ name: 'why3d', title: '优势3说明', type: 'text', rows: 2 }),
        defineField({ name: 'why4t', title: '优势4标题', type: 'string' }),
        defineField({ name: 'why4d', title: '优势4说明', type: 'text', rows: 2 }),
        defineField({ name: 'worldEyebrow', title: '全球模块眉题', type: 'string' }),
        defineField({ name: 'worldTitle1', title: '全球模块标题第一行', type: 'string' }),
        defineField({ name: 'worldTitle2', title: '全球模块标题第二行', type: 'string' }),
        defineField({ name: 'worldLead', title: '全球模块导语', type: 'text', rows: 2 }),
        defineField({ name: 'worldLawT', title: '全球模块卡片1标题', type: 'string' }),
        defineField({ name: 'worldLawD', title: '全球模块卡片1说明', type: 'text', rows: 2 }),
        defineField({ name: 'worldLogT', title: '全球模块卡片2标题', type: 'string' }),
        defineField({ name: 'worldLogD', title: '全球模块卡片2说明', type: 'text', rows: 2 }),
        defineField({ name: 'featEyebrow', title: '精选产品模块眉题', type: 'string' }),
        defineField({ name: 'featTitle', title: '精选产品模块标题', type: 'string' }),
        defineField({ name: 'casesEyebrow', title: '案例模块眉题', type: 'string' }),
        defineField({ name: 'casesTitle', title: '案例模块标题', type: 'string' }),
        defineField({ name: 'faqSectionLead', title: 'FAQ 模块导语', type: 'text', rows: 2 }),
        defineField({ name: 'browseFullGuide', title: 'FAQ 模块按钮文案', type: 'string' }),
      ],
    }),
    defineField({
      name: 'sections',
      title: '扩展模块（预留）',
      type: 'array',
      group: 'content',
      description: '后续可接入更多自定义区块类型',
      of: [
        {
          type: 'object',
          name: 'homeRichSection',
          title: '富文本块',
          fields: [
            defineField({ name: 'heading', title: '小标题', type: 'string' }),
            defineField({ name: 'body', title: '正文', type: 'blockContent' }),
          ],
        },
      ],
    }),
    defineField({
      name: 'locale',
      title: '语言标记（预留）',
      type: 'string',
      description: '与 siteSettings.localeDefault 对齐时可区分多语言首页',
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      group: 'seo',
    }),
  ],
  preview: {
    prepare: () => ({ title: '首页' }),
  },
});
