import { defineField, defineType } from 'sanity';

export default defineType({
  name: 'product',
  title: '产品',
  type: 'document',
  groups: [
    { name: 'main', title: '基础' },
    { name: 'content', title: '详情' },
    { name: 'translations', title: '翻译（自动）' },
    { name: 'meta', title: '展示设置' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'name',
      title: '名称',
      type: 'string',
      group: 'main',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'main',
      options: { source: 'name', maxLength: 96 },
    }),
    defineField({
      name: 'category',
      title: '分类',
      type: 'reference',
      to: [{ type: 'productCategory' }],
      group: 'main',
    }),
    defineField({
      name: 'mainImage',
      title: '封面 / 主图',
      type: 'image',
      options: { hotspot: true },
      group: 'main',
    }),
    defineField({
      name: 'gallery',
      title: '图库',
      type: 'array',
      group: 'main',
      of: [{ type: 'image', options: { hotspot: true } }],
    }),
    defineField({
      name: 'excerpt',
      title: '摘要',
      type: 'text',
      rows: 3,
      group: 'content',
    }),
    defineField({
      name: 'description',
      title: '短描述（列表用）',
      type: 'text',
      rows: 4,
      group: 'content',
    }),
    defineField({
      name: 'body',
      title: '详情正文',
      type: 'blockContent',
      group: 'content',
    }),
    defineField({
      name: 'specifications',
      title: '参数 / 规格',
      type: 'array',
      group: 'content',
      of: [
        {
          type: 'object',
          name: 'specRow',
          fields: [
            defineField({ name: 'label', title: '名称', type: 'string' }),
            defineField({ name: 'value', title: '值', type: 'string' }),
            // 自动翻译（由 Webhook 写入，勿手动编辑）
            defineField({ name: 'label_en', title: 'Label (EN)', type: 'string', readOnly: true }),
            defineField({ name: 'label_es', title: 'Label (ES)', type: 'string', readOnly: true }),
            defineField({ name: 'label_pt', title: 'Label (PT)', type: 'string', readOnly: true }),
            defineField({ name: 'label_ar', title: 'Label (AR)', type: 'string', readOnly: true }),
            defineField({ name: 'label_ru', title: 'Label (RU)', type: 'string', readOnly: true }),
            defineField({ name: 'value_en', title: 'Value (EN)', type: 'string', readOnly: true }),
            defineField({ name: 'value_es', title: 'Value (ES)', type: 'string', readOnly: true }),
            defineField({ name: 'value_pt', title: 'Value (PT)', type: 'string', readOnly: true }),
            defineField({ name: 'value_ar', title: 'Value (AR)', type: 'string', readOnly: true }),
            defineField({ name: 'value_ru', title: 'Value (RU)', type: 'string', readOnly: true }),
          ],
          preview: {
            select: { l: 'label', v: 'value' },
            prepare({ l, v }) {
              return { title: `${l}: ${v}` };
            },
          },
        },
      ],
    }),
    defineField({
      name: 'applicationScenarios',
      title: '应用场景',
      type: 'text',
      rows: 4,
      group: 'content',
    }),
    defineField({ name: 'tags', title: '标签', type: 'array', group: 'content', of: [{ type: 'string' }] }),
    defineField({ name: 'packaging', title: '包装建议', type: 'string', group: 'content' }),
    defineField({ name: 'supportOem', title: '支持 OEM', type: 'boolean', initialValue: true, group: 'content' }),
    defineField({ name: 'skinType', title: '适用肤质/人群', type: 'string', group: 'content' }),
    defineField({
      name: 'ingredients',
      title: '成分',
      type: 'array',
      of: [{ type: 'ingredient' }],
      group: 'content',
    }),
    defineField({
      name: 'efficacy',
      title: '功效要点（每行一条）',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'content',
    }),
    defineField({ name: 'oemDesc', title: 'OEM/定制说明', type: 'text', rows: 4, group: 'content' }),

    // ── 自动翻译字段（由 Webhook 写入，勿手动编辑）──────────────────
    defineField({ name: 'name_en', title: 'Name (EN)', type: 'string', group: 'translations', readOnly: true,
      description: '由翻译 Webhook 自动填充，请勿手动编辑' }),
    defineField({ name: 'name_es', title: 'Name (ES)', type: 'string', group: 'translations', readOnly: true }),
    defineField({ name: 'name_pt', title: 'Name (PT)', type: 'string', group: 'translations', readOnly: true }),
    defineField({ name: 'name_ar', title: 'Name (AR)', type: 'string', group: 'translations', readOnly: true }),
    defineField({ name: 'name_ru', title: 'Name (RU)', type: 'string', group: 'translations', readOnly: true }),
    defineField({ name: 'excerpt_en', title: 'Excerpt (EN)', type: 'text', rows: 3, group: 'translations', readOnly: true }),
    defineField({ name: 'excerpt_es', title: 'Excerpt (ES)', type: 'text', rows: 3, group: 'translations', readOnly: true }),
    defineField({ name: 'excerpt_pt', title: 'Excerpt (PT)', type: 'text', rows: 3, group: 'translations', readOnly: true }),
    defineField({ name: 'excerpt_ar', title: 'Excerpt (AR)', type: 'text', rows: 3, group: 'translations', readOnly: true }),
    defineField({ name: 'excerpt_ru', title: 'Excerpt (RU)', type: 'text', rows: 3, group: 'translations', readOnly: true }),
    defineField({ name: 'description_en', title: 'Description (EN)', type: 'text', rows: 4, group: 'translations', readOnly: true }),
    defineField({ name: 'description_es', title: 'Description (ES)', type: 'text', rows: 4, group: 'translations', readOnly: true }),
    defineField({ name: 'description_pt', title: 'Description (PT)', type: 'text', rows: 4, group: 'translations', readOnly: true }),
    defineField({ name: 'description_ar', title: 'Description (AR)', type: 'text', rows: 4, group: 'translations', readOnly: true }),
    defineField({ name: 'description_ru', title: 'Description (RU)', type: 'text', rows: 4, group: 'translations', readOnly: true }),
    defineField({ name: 'applicationScenarios_en', title: 'Application Scenarios (EN)', type: 'text', rows: 4, group: 'translations', readOnly: true }),
    defineField({ name: 'applicationScenarios_es', title: 'Application Scenarios (ES)', type: 'text', rows: 4, group: 'translations', readOnly: true }),
    defineField({ name: 'applicationScenarios_pt', title: 'Application Scenarios (PT)', type: 'text', rows: 4, group: 'translations', readOnly: true }),
    defineField({ name: 'applicationScenarios_ar', title: 'Application Scenarios (AR)', type: 'text', rows: 4, group: 'translations', readOnly: true }),
    defineField({ name: 'applicationScenarios_ru', title: 'Application Scenarios (RU)', type: 'text', rows: 4, group: 'translations', readOnly: true }),
    defineField({ name: 'packaging_en', title: 'Packaging (EN)', type: 'string', group: 'translations', readOnly: true }),
    defineField({ name: 'packaging_es', title: 'Packaging (ES)', type: 'string', group: 'translations', readOnly: true }),
    defineField({ name: 'packaging_pt', title: 'Packaging (PT)', type: 'string', group: 'translations', readOnly: true }),
    defineField({ name: 'packaging_ar', title: 'Packaging (AR)', type: 'string', group: 'translations', readOnly: true }),
    defineField({ name: 'packaging_ru', title: 'Packaging (RU)', type: 'string', group: 'translations', readOnly: true }),
    defineField({ name: 'skinType_en', title: 'Skin Type (EN)', type: 'string', group: 'translations', readOnly: true }),
    defineField({ name: 'skinType_es', title: 'Skin Type (ES)', type: 'string', group: 'translations', readOnly: true }),
    defineField({ name: 'skinType_pt', title: 'Skin Type (PT)', type: 'string', group: 'translations', readOnly: true }),
    defineField({ name: 'skinType_ar', title: 'Skin Type (AR)', type: 'string', group: 'translations', readOnly: true }),
    defineField({ name: 'skinType_ru', title: 'Skin Type (RU)', type: 'string', group: 'translations', readOnly: true }),
    defineField({ name: 'oemDesc_en', title: 'OEM Desc (EN)', type: 'text', rows: 4, group: 'translations', readOnly: true }),
    defineField({ name: 'oemDesc_es', title: 'OEM Desc (ES)', type: 'text', rows: 4, group: 'translations', readOnly: true }),
    defineField({ name: 'oemDesc_pt', title: 'OEM Desc (PT)', type: 'text', rows: 4, group: 'translations', readOnly: true }),
    defineField({ name: 'oemDesc_ar', title: 'OEM Desc (AR)', type: 'text', rows: 4, group: 'translations', readOnly: true }),
    defineField({ name: 'oemDesc_ru', title: 'OEM Desc (RU)', type: 'text', rows: 4, group: 'translations', readOnly: true }),
    defineField({ name: 'efficacy_en', title: 'Efficacy (EN)', type: 'array', of: [{ type: 'string' }], group: 'translations', readOnly: true }),
    defineField({ name: 'efficacy_es', title: 'Efficacy (ES)', type: 'array', of: [{ type: 'string' }], group: 'translations', readOnly: true }),
    defineField({ name: 'efficacy_pt', title: 'Efficacy (PT)', type: 'array', of: [{ type: 'string' }], group: 'translations', readOnly: true }),
    defineField({ name: 'efficacy_ar', title: 'Efficacy (AR)', type: 'array', of: [{ type: 'string' }], group: 'translations', readOnly: true }),
    defineField({ name: 'efficacy_ru', title: 'Efficacy (RU)', type: 'array', of: [{ type: 'string' }], group: 'translations', readOnly: true }),
    defineField({ name: 'tags_en', title: 'Tags (EN)', type: 'array', of: [{ type: 'string' }], group: 'translations', readOnly: true }),
    defineField({ name: 'tags_es', title: 'Tags (ES)', type: 'array', of: [{ type: 'string' }], group: 'translations', readOnly: true }),
    defineField({ name: 'tags_pt', title: 'Tags (PT)', type: 'array', of: [{ type: 'string' }], group: 'translations', readOnly: true }),
    defineField({ name: 'tags_ar', title: 'Tags (AR)', type: 'array', of: [{ type: 'string' }], group: 'translations', readOnly: true }),
    defineField({ name: 'tags_ru', title: 'Tags (RU)', type: 'array', of: [{ type: 'string' }], group: 'translations', readOnly: true }),
    defineField({
      name: 'bodyPlain_en',
      title: '详情正文（纯文本 EN，自动）',
      type: 'text',
      rows: 6,
      group: 'translations',
      readOnly: true,
      description: '由 Webhook 从「详情正文」抽取并翻译，前台英文站用于展示',
    }),
    defineField({
      name: 'bodyPlain_es',
      title: '详情正文（纯文本 ES，自动）',
      type: 'text',
      rows: 6,
      group: 'translations',
      readOnly: true,
    }),
    defineField({
      name: 'bodyPlain_pt',
      title: '详情正文（纯文本 PT，自动）',
      type: 'text',
      rows: 6,
      group: 'translations',
      readOnly: true,
    }),
    defineField({
      name: 'bodyPlain_ar',
      title: '详情正文（纯文本 AR，自动）',
      type: 'text',
      rows: 6,
      group: 'translations',
      readOnly: true,
    }),
    defineField({
      name: 'bodyPlain_ru',
      title: '详情正文（纯文本 RU，自动）',
      type: 'text',
      rows: 6,
      group: 'translations',
      readOnly: true,
    }),
    // 内容哈希，用于防止翻译 Webhook 循环触发
    defineField({ name: 'translationSourceHash', title: '翻译源哈希', type: 'string', group: 'translations', readOnly: true,
      hidden: true }),

    defineField({
      name: 'sortOrder',
      title: '排序',
      type: 'number',
      initialValue: 0,
      group: 'meta',
    }),
    defineField({
      name: 'isFeatured',
      title: '精选 / 推荐位',
      type: 'boolean',
      initialValue: false,
      group: 'meta',
    }),
    defineField({
      name: 'isPublished',
      title: '前台展示',
      type: 'boolean',
      initialValue: true,
      group: 'meta',
    }),
    defineField({ name: 'locale', title: '语言（预留）', type: 'string', group: 'meta' }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      group: 'seo',
    }),
  ],
  preview: {
    select: { title: 'name', media: 'mainImage', cat: 'category.title' },
    prepare({ title, media, cat }) {
      return { title, subtitle: cat || '', media };
    },
  },
});
