import { defineField, defineType } from 'sanity';

const LANGS = [
  { suffix: '', label: '中文（默认）' },
  { suffix: '_en', label: 'EN' },
  { suffix: '_es', label: 'ES' },
  { suffix: '_pt', label: 'PT' },
  { suffix: '_ar', label: 'AR' },
  { suffix: '_ru', label: 'RU' },
];

function localizedFields(name, title, type = 'string', extra = {}) {
  return LANGS.map((lang) =>
    defineField({
      name: `${name}${lang.suffix}`,
      title: `${title}（${lang.label}）`,
      type,
      ...extra,
    }),
  );
}

const baseRows = [
  ['eyebrow', '页眉文案'],
  ['h1l1', '主标题第一行'],
  ['h1l2', '主标题第二行'],
  ['lead', '导语', 'text', { rows: 3 }],
  ['cta', '主按钮文案'],
  ['modelsTitle', '服务模式标题'],
  ['modelsLead', '服务模式导语', 'text', { rows: 2 }],
  ['oemTagline', 'OEM 英文标签'],
  ['oemH', 'OEM 标题'],
  ['oemP', 'OEM 说明', 'text', { rows: 3 }],
  ['oemL1', 'OEM 要点 1'],
  ['oemL2', 'OEM 要点 2'],
  ['oemL3', 'OEM 要点 3'],
  ['odmTagline', 'ODM 英文标签'],
  ['odmH', 'ODM 标题'],
  ['odmP', 'ODM 说明', 'text', { rows: 3 }],
  ['odmL1', 'ODM 要点 1'],
  ['odmL2', 'ODM 要点 2'],
  ['odmL3', 'ODM 要点 3'],
  ['obmTagline', 'OBM 英文标签'],
  ['obmH', 'OBM 标题'],
  ['obmP', 'OBM 说明', 'text', { rows: 3 }],
  ['obmL1', 'OBM 要点 1'],
  ['obmL2', 'OBM 要点 2'],
  ['obmL3', 'OBM 要点 3'],
  ['flowTitle', '流程标题'],
  ['flowLead', '流程导语', 'text', { rows: 2 }],
  ['flow1t', '流程 1 标题'],
  ['flow1d', '流程 1 说明', 'text', { rows: 3 }],
  ['flow2t', '流程 2 标题'],
  ['flow2d', '流程 2 说明', 'text', { rows: 3 }],
  ['flow3t', '流程 3 标题'],
  ['flow3d', '流程 3 说明', 'text', { rows: 3 }],
  ['flow4t', '流程 4 标题'],
  ['flow4d', '流程 4 说明', 'text', { rows: 3 }],
  ['capEyebrow', '产能模块眉题'],
  ['capTitle', '产能模块标题'],
  ['capLead', '产能模块导语', 'text', { rows: 2 }],
  ['cap1t', '能力卡片 1 标题'],
  ['cap1d', '能力卡片 1 说明', 'text', { rows: 3 }],
  ['cap2t', '能力卡片 2 标题'],
  ['cap2d', '能力卡片 2 说明', 'text', { rows: 3 }],
];

const initialValue = {
  eyebrow: 'Global Cosmetic Manufacturing',
  h1l1: '从卓越概念，',
  h1l2: '到全球热销单品。',
  lead:
    '依托符合国际 GMPC 及 ISO 22716 标准的智慧工厂，\nYOZO 提供贯穿产品生命周期的端到端制造解决方案。赋能品牌高效出海，构筑核心产品护城河。',
  cta: '获取专属代工方案',
  modelsTitle: '适应多维商业周期的全链路智造引擎',
  modelsLead: '无论您是寻求产能突破的国际大牌，还是从 0 孵化的新锐国货，我们均提供高匹配度的柔性制造模块。',
  oemTagline: 'Original Equipment Mfg',
  oemH: 'OEM 敏捷代工',
  oemP: '您提供核心配方或品牌标准，我们依托 10 万级无尘自动化产线进行高标准复刻，保障大批量品质一致性与极致的成本控制。',
  oemL1: '严苛的原料溯源与来料质检 (IQC)',
  oemL2: '日均超百万支的柔性灌装产能',
  oemL3: '符合 FDA/CPNP 的出厂检测标准',
  odmTagline: 'Original Design Mfg',
  odmH: 'ODM 深度定制研发',
  odmP: '整合全球顶级原料供应链与临床测试数据。从前瞻性的市场趋势企划、专属独家配方研发，到特殊包材结构开模，构筑绝对技术壁垒。',
  odmL1: '诺奖级核心成分/植物提取复配研发',
  odmL2: '3D皮肤模型及人体功效实证测试',
  odmL3: '配方知识产权 (IP) 排他性买断支持',
  obmTagline: 'Private Label / OBM',
  obmH: '品牌贴牌全案孵化',
  obmP: '专为电商达人及跨界品牌打造。精选 10,000+ 经过市场验证的成熟爆款配方库，支持极低门槛启动 (Low MOQ) 与保姆级落地方案。',
  obmL1: '3-5天极速打样确认，抢占风口',
  obmL2: '免费品牌视觉设计与包材选型',
  obmL3: '药监局非特备案及特证代办服务',
  flowTitle: '标准化与透明化的高端代工流程',
  flowLead: '全链路数据驱动，拒绝“制造黑盒”，保障您的新品以最高效的速度推向全球市场。',
  flow1t: '需求企划与对接',
  flow1d: '专属业务总监 1对1 沟通。确立核心受众、功效宣称诉求、包材材质偏好及成本核算。',
  flow2t: '联合实验室打样',
  flow2d: '资深配方师介入，调取数据库或重构配方体系。常规需求最快 3 天输出首版实物样品供评测。',
  flow3t: '评测与合规备案',
  flow3d: '进行高低温稳定性挑战测试及理化防腐测试。同时法务团队平行推进药监系统产品备案核准。',
  flow4t: 'GMPC量产与交付',
  flow4d: '大货包材消毒入库，MES系统排单投料生产。全检合格后提供检测报告，并无缝对接跨境物流。',
  capEyebrow: 'Core Capacities',
  capTitle: '驱动创新的核心工艺配置',
  capLead: '不仅局限于传统的膏霜水乳，我们斥资引进国际尖端设备，全面覆盖高难度剂型及医药级无菌包装生产线。',
  cap1t: 'BFS 无菌次抛与冻干线',
  cap1d:
    '百级净化核心产区。配备吹灌封 (Blow-Fill-Seal) 一体机及真空冷冻干燥机，专攻高活性维C、蓝铜胜肽及冻干粉产品，确保无防腐剂添加条件下的绝佳鲜活度。',
  cap2t: '多相微乳化与微囊包裹工艺',
  cap2d:
    '引进德国 IKA 高剪切均质乳化系统。突破传统水油相融限制，实现纳米级粒径乳液。通过微脂囊技术实现核心活性成分的定向靶向缓释。',
  eyebrow_en: 'Global Cosmetic Manufacturing',
  h1l1_en: 'From a bold concept,',
  h1l2_en: 'to a global bestseller.',
  lead_en:
    'YOZO runs an ISO 22716 / GMPC-aligned smart plant—end-to-end manufacturing across the product lifecycle for efficient global scale.',
  cta_en: 'Get a tailored OEM plan',
  modelsTitle_en: 'A full-chain engine for every growth stage',
  modelsLead_en: 'From global majors to day-one brands—modular, flexible manufacturing.',
  oemTagline_en: 'Original Equipment Mfg',
  oemH_en: 'OEM agile production',
  oemP_en: 'Your formula or brand standard, replicated at scale with consistent quality and cost control.',
  oemL1_en: 'Rigorous ingredient traceability & IQC',
  oemL2_en: 'Flexible filling capacity at million-unit scale',
  oemL3_en: 'Release testing aligned with FDA / CPNP expectations',
  odmTagline_en: 'Original Design Mfg',
  odmH_en: 'ODM R&D partnership',
  odmP_en: 'Trend insight, exclusive formulas, and custom packaging structures—real technical differentiation.',
  odmL1_en: 'Advanced actives & botanical complexes',
  odmL2_en: '3D skin models and human efficacy studies',
  odmL3_en: 'Optional exclusive IP buyout for custom formulas',
  obmTagline_en: 'Private Label / OBM',
  obmH_en: 'Private label incubation',
  obmP_en: '10,000+ market-tested formulas, low MOQ, and hands-on go-to-market support.',
  obmL1_en: 'Sampling in 3–5 days to catch trends',
  obmL2_en: 'Brand visuals & packaging selection support',
  obmL3_en: 'Domestic filing and special-license assistance',
  flowTitle_en: 'Transparent, premium OEM workflow',
  flowLead_en: 'Data-driven visibility—no manufacturing black boxes.',
  flow1t_en: 'Discovery & planning',
  flow1d_en: 'Dedicated director; audience, claims, packaging, and cost alignment.',
  flow2t_en: 'Lab prototyping',
  flow2d_en: 'Formulators rebuild or adapt formulas—first samples in as fast as 3 days.',
  flow3t_en: 'Testing & filing',
  flow3d_en: 'Stability & preservative challenge; regulatory filing in parallel.',
  flow4t_en: 'GMPC scale-up & delivery',
  flow4d_en: 'MES-scheduled production, COA release, and logistics handoff.',
  capEyebrow_en: 'Core Capacities',
  capTitle_en: 'Advanced process configuration',
  capLead_en: 'Beyond creams and lotions—specialized formats and aseptic lines.',
  cap1t_en: 'BFS ampoules & lyophilization',
  cap1d_en: 'Grade-A core zones, BFS and freeze-drying for sensitive actives without preservatives.',
  cap2t_en: 'Multi-phase emulsion & encapsulation',
  cap2d_en: 'IKA high-shear systems for nano emulsions and targeted release.',
  eyebrow_es: 'Global Cosmetic Manufacturing',
  h1l1_es: 'De un gran concepto,',
  h1l2_es: 'a un éxito global.',
  lead_es:
    'Planta inteligente ISO 22716 / GMPC—fabricación de todo el ciclo de vida para escalar con eficiencia.',
  cta_es: 'Obtener plan OEM',
  modelsTitle_es: 'Motor integral para cada etapa',
  modelsLead_es: 'De grandes marcas a startups—fabricación modular y flexible.',
  oemTagline_es: 'Original Equipment Mfg',
  oemH_es: 'Producción OEM ágil',
  oemP_es: 'Su fórmula o estándar, replicado a escala con calidad y coste.',
  oemL1_es: 'Trazabilidad e IQC rigurosos',
  oemL2_es: 'Capacidad de llenado flexible a escala millón',
  oemL3_es: 'Liberación alineada con FDA / CPNP',
  odmTagline_es: 'Original Design Mfg',
  odmH_es: 'I+D ODM',
  odmP_es: 'Tendencias, fórmulas exclusivas y envases especiales.',
  odmL1_es: 'Activos avanzados y complejos botánicos',
  odmL2_es: 'Piel 3D y estudios de eficacia humana',
  odmL3_es: 'Compra exclusiva opcional de PI',
  obmTagline_es: 'Private Label / OBM',
  obmH_es: 'Incubación private label',
  obmP_es: '10.000+ fórmulas probadas, MOQ bajo y acompañamiento.',
  obmL1_es: 'Muestreo 3–5 días',
  obmL2_es: 'Apoyo visual y envase',
  obmL3_es: 'Trámites regulatorios locales',
  flowTitle_es: 'Flujo OEM transparente',
  flowLead_es: 'Datos visibles—sin cajas negras.',
  flow1t_es: 'Descubrimiento',
  flow1d_es: 'Director dedicado; audiencia, claims, envase y coste.',
  flow2t_es: 'Prototipo en laboratorio',
  flow2d_es: 'Reformulación—primeras muestras en ~3 días.',
  flow3t_es: 'Ensayos y registros',
  flow3d_es: 'Estabilidad y desafío conservante; registro en paralelo.',
  flow4t_es: 'Escala GMPC y entrega',
  flow4d_es: 'MES, COA y logística.',
  capEyebrow_es: 'Core Capacities',
  capTitle_es: 'Procesos avanzados',
  capLead_es: 'Más allá de cremas—formatos especiales y líneas asépticas.',
  cap1t_es: 'BFS y liofilización',
  cap1d_es: 'Zonas clase A, BFS y liofilizado para activos sensibles.',
  cap2t_es: 'Emulsión multfase y microcápsulas',
  cap2d_es: 'Sistemas IKA de alto corte y liberación dirigida.',
};

export default defineType({
  name: 'servicePage',
  title: '代工方案页',
  type: 'document',
  fields: [
    ...baseRows.flatMap(([name, title, type, extra]) => localizedFields(name, title, type, extra)),
    defineField({
      name: 'translationSourceHash',
      title: '翻译源哈希',
      type: 'string',
      readOnly: true,
      hidden: true,
    }),
  ],
  preview: {
    prepare: () => ({ title: '代工方案页' }),
  },
  initialValue,
});
